//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatinhasMimadas.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatinhasMimadas.Common.Resources.LabelResources", typeof(LabelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde que abrimos as nossas portas, a Patinhas Mimadas estabelece um compromisso com a satisfação do cliente. A empresa não seria o que é hoje se não fosse pelo incentivo de manter esse padrão de excelência..
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acreditamos que é essencial colocar o cliente em primeiro lugar, oferecendo produtos e serviços excecionais. Entre em contacto connosco hoje mesmo para conhecer as nossas ofertas..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venha nos visitar.
        /// </summary>
        public static string ComeVisitUs {
            get {
                return ResourceManager.GetString("ComeVisitUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta é a descrição de um produto. Escreva um texto geral curto que inclui os recursos importantes, preço e informações relevantes para o futuro comprador. Considere adicionar uma imagem ou vídeo que mostre a beleza do seu produto e incentive o seu visitante a fazer a compra..
        /// </summary>
        public static string DogSelfServiceDescription {
            get {
                return ResourceManager.GetString("DogSelfServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta é a descrição de um produto. Escreva um texto geral curto que inclui os recursos importantes, preço e informações relevantes para o futuro comprador. Considere adicionar uma imagem ou vídeo que mostre a beleza do seu produto e incentive o seu visitante a fazer a compra..
        /// </summary>
        public static string DogSittingDescription {
            get {
                return ResourceManager.GetString("DogSittingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta é a descrição de um produto. Escreva um texto geral curto que inclui os recursos importantes, preço e informações relevantes para o futuro comprador. Considere adicionar uma imagem ou vídeo que mostre a beleza do seu produto e incentive o seu visitante a fazer a compra..
        /// </summary>
        public static string DogWashDescription {
            get {
                return ResourceManager.GetString("DogWashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá !.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seg - Sex: 9:00 - 18:00
        ///                &lt;br /&gt; Sáb: 10:00 - 14:00
        ///                &lt;br /&gt; Dom: Fechado.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
    }
}
